### ISSUE TITLE
do yall still have the discord or another one?

### ISSUE THREAD

**Issue by Dylanomeneer** [Pete9xi/Paradox_AntiCheat#25]
please i need to be updated

**Comment by Pete9xi** [comment]
Link in the readme

**Comment by Dylanomeneer** [comment]
Think I'm banned not sure why, i was helping people in the Discord, could you maybe check? My user is 
<bub>#0837

**Comment by Pete9xi** [comment]
Not seeing that tag in the logs try joining again

**Comment by Visual1mpact** [comment]
@Dylanomeneer  in case you didn't find the correct one.

https://discord.gg/qVd53N2xhq
