### ISSUE TITLE
Docs - Mobile Navbar Behavior

### ISSUE THREAD

**Issue by DJStompZone** [Pete9xi/Paradox_AntiCheat#30]
### Bug Description
When viewing the docs on Chrome for Android, the navbar closes at inappropriate/unexpected times. 

Clicking on a category (which does not redirect the user) causes the navbar to close unexpectedly. This gives the appearance of a redirect while actually remaining on the current page. 

### Bug Reproduction

- Open the navbar
- Click on a category (Guides, Support, etc)
- Experience momentary bewilderment
- Re-open navbar
- Continue navigation

### Expectation
The navbar should remain open until the user selects a navigable item or clicks away. 

### Reality 
The navbar closes when a category is selected.
It must then be re-opened to access the link to the desired page. 

### Environment
**Browser**: Chrome for Android (v117) 
**OS**: Android (13.0)
**Device**: Pixel 6a (MP1.0)

### Additional context
`const ctx = null`

**Comment by Visual1mpact** [comment]
I can confirm that this behavior exists. It appears to stem from docsify-sidebar-collapse.min.js in the handleMenuClick function.

**Comment by Visual1mpact** [comment]
Made some changes that should bring some closure to this. Feel free to create another issue if there are still problems or send a PR.

https://github.com/Pete9xi/Paradox_AntiCheat/commit/b23dd357f951713be2749275e810f6714dd1947d

https://github.com/Pete9xi/Paradox_AntiCheat/commit/892ef63961032c2464ae3380e969b9ae9183d959
